-- Capture jobs: work ordered from a capture subcontractor.
--
-- Hand-written rather than generated by `prisma migrate dev`, which wants to
-- reset the development database because earlier migrations were edited after
-- being applied and no longer match their checksums.

CREATE TYPE "CaptureJobStatus" AS ENUM ('DRAFT', 'ISSUED', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'CANCELLED');
CREATE TYPE "CaptureJobSiteStatus" AS ENUM ('PENDING', 'IN_PROGRESS', 'SUBMITTED', 'ACCEPTED', 'REJECTED');
CREATE TYPE "CaptureDeliverable" AS ENUM ('DRONE', 'MATTERPORT', 'IMAGE_360', 'PHOTOS', 'CONDITION_SCORES');

CREATE TABLE "CaptureJob" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "vendorId" TEXT,
    "title" TEXT NOT NULL,
    "instructions" TEXT,
    "status" "CaptureJobStatus" NOT NULL DEFAULT 'DRAFT',
    "dueDate" TIMESTAMP(3),
    "issuedAt" TIMESTAMP(3),
    "submittedAt" TIMESTAMP(3),
    "closedAt" TIMESTAMP(3),
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "CaptureJob_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "CaptureJobSite" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "propertyId" TEXT NOT NULL,
    "deliverables" "CaptureDeliverable"[],
    "status" "CaptureJobSiteStatus" NOT NULL DEFAULT 'PENDING',
    "notes" TEXT,
    "submittedAt" TIMESTAMP(3),
    "reviewedAt" TIMESTAMP(3),
    "reviewedById" TEXT,
    "rejectionReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "CaptureJobSite_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "CaptureJob_organizationId_status_idx" ON "CaptureJob"("organizationId", "status");
CREATE INDEX "CaptureJob_vendorId_status_idx" ON "CaptureJob"("vendorId", "status");
CREATE INDEX "CaptureJobSite_propertyId_idx" ON "CaptureJobSite"("propertyId");
-- A site appears on a job once: two rows would let one submission satisfy the
-- other and make the completion count wrong.
CREATE UNIQUE INDEX "CaptureJobSite_jobId_propertyId_key" ON "CaptureJobSite"("jobId", "propertyId");

ALTER TABLE "CaptureJob" ADD CONSTRAINT "CaptureJob_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CaptureJob" ADD CONSTRAINT "CaptureJob_vendorId_fkey" FOREIGN KEY ("vendorId") REFERENCES "Vendor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CaptureJob" ADD CONSTRAINT "CaptureJob_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CaptureJobSite" ADD CONSTRAINT "CaptureJobSite_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "CaptureJob"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CaptureJobSite" ADD CONSTRAINT "CaptureJobSite_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CaptureJobSite" ADD CONSTRAINT "CaptureJobSite_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
